using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DashboardAPI.Migrations
{
    public partial class FixUsersIdSequence : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // La migración AddUsers fue generada con SQLite, por lo que la columna Id
            // quedó como INTEGER NOT NULL sin secuencia en PostgreSQL. EF intenta
            // insertar con Id=null y PostgreSQL lo rechaza (23502).
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql(@"ALTER TABLE ""Users"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;");
            }
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql(@"ALTER TABLE ""Users"" ALTER COLUMN ""Id"" DROP IDENTITY IF EXISTS;");
            }
        }
    }
}
